version: '3.9'
services:
    build:
        image: node:22.14.0-alpine
        volumes:
            - .:/src
        working_dir: /src
        command: "sh -i -c 'npm ci && npm run build'"
    nginx:
        image: nginx:1.27.4-alpine
        volumes:
            - ./public:/usr/share/nginx/html
        ports:
            - '8080:80'
