name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: nvm use v22.14.0
        uses: actions/setup-node@v2
        with:
          node-version: '22.14.0'
      - run: npm ci
      - run: npm run check
      - run: npm run build:ts
      - run: npm test
